name: LyttleDisguise
description: Custom disguise plugin
version: '${projectVersion}'
main: com.lyttledev.lyttledisguise.LyttleDisguise
api-version: '1.21'
authors:
  - LyttleDevelopment
  - ThatsATim
  - Stualyttle

soft-dependencies:
  - PlaceholderAPI
  - LuckPerms

commands:
  lyttledisguise:
    description: Admin command, mainly reload the config without the rest of the server
    permission: lyttledisguise.lyttledisguise

  disguise:
    description: Disguise as an entity or another player
    usage: /disguise <entity|player|username|skinname|clear> <value>
    permission: lyttledisguise.disguise